templates/filebeat.yml
Without this change the line after the hosts block will get indented and the application will throw a yaml parser error on startup: `Loading config file error: YAML config parsing failed on /etc/filebeat/filebeat.yml: yaml: line 22: did not find expected '-' indicator. Exiting.`
`/etc/filebeat/filebeat.yml` generated before change:
filebeat:
prospectors:
-
paths:
- /var/log/*.log
input_type: log
exclude_files: [".gz$"]
scan_frequency: 10s
harvester_buffer_size: 16384
max_bytes: 10485760.0
registry_file: /var/lib/filebeat/registry
logging:
to_syslog: true
output:
logstash:
hosts:
- "172.16.0.133:5044"
worker: 1
compression_level: 3
loadbalance: true
shipper:
name: nova-compute/1
Note the indentation after the hosts block.
File generated after change:
filebeat:
prospectors:
-
paths:
- …
=> Fix filebeat hosts generation block

config.yaml, reactive/filebeat.py, templates/filebeat.yml, tests/30-deploy-with-logstash-hosts
This allows logstash to be running in a different model.
=> Add configuration option for logstash output hosts.

config.yaml, templates/filebeat.yml
We found the requirement to set exclude_files since the logpath option is so broad.
I added exclude_lines because it seemed to fit.
=> Add exclude_* config options

reactive/filebeat.py
Fixes https://github.com/juju-solutions/layer-beats-base/issues/16
=> Support for fully removing relations

config.yaml, templates/filebeat.yml
Add a prospector specific for shipping logs from Kubernetes pods.
The prospector is needed as Kubernetes logs are formatted in json and are not picked up by the default prospector.
=> added simple configuration option to support shipping logs from Kubernetes pods

README.md, reactive/filebeat.py
- Update some out-of-date language in the readme (`service` -> `application`, `set-config` -> `config`, etc).
- fix a typo in one of the handler names (s/packetbeat/filebeat).
This is in the edge channel at rev 10:
https://jujucharms.com/filebeat/10
=> readme refresh

tests/10-deploy-with-logstash, tests/20-deploy-with-elasticsearch, tests/30-deploy-with-logstash-hosts, tests/40-deploy-with-kafka, tests/50-deploy-with-kafka-hosts
Also drive-by fix in `tests/40-deploy-with-kafka`:
- s/elasticsearch/kafka since there is no elasticsearch charm in this test
=> use xenial for filebeat amulet tests

README.md
The elk-stack has moved to the ~elasticsearch-charmers namespace. Update the readme usage to reflect that, and make sure we instruct people to use xenial charms.
=> update readme with new elk-stack namespace

reactive/filebeat.py
The ssl certs are not being created at install time due to the render_filebeat_template() function being called first and then changing the state so the render_filebeat_logstash_ssl_cert() function will not be called.
This change ensures that whenever the render_filebeat_template() function re-renders the config file it also re-renders the certs, ensuring they are correctly created at install time
=> render the ssl certs on install/update

reactive/filebeat.py
As mentioned in #46, we don't need to call both `render_*` functions with the same `@when` decorators.  Combine the `restart_on_change` maps (which dedupes to restart `filebeat` only once if any of the mapped config files change) so we handle both config and ssl certs under a single set of reactive conditions.
Strictly speaking, `render_filebeat_logstash_ssl_cert` isn't reactive any more, so it probably belongs in a `./lib/charm/layer` library. Given the importance of fixing #46, we can address this later.
=> follow-on to #46: ensure config/ssl is rendered by a single handler

layer.yaml, metadata.yaml, reactive/filebeat.py
Depends on: https://github.com/juju-solutions/layer-beats-base/pull/27
This PR adds support for re-installing filebeat when the apt repo changes:
- let initial installation and app version happen with an apt layer option
- refactor status to use [layer-status](https://github.com/juju-solutions/layer-status)
- new handlers to react to changes in the apt repo
- get rid of all filebeat traces if we stop (all beats should be nice and clean up if/when they are removed from their principal units)
=> enable the reinstall action

tests/10-deploy-with-logstash, tests/20-deploy-with-elasticsearch, tests/30-deploy-with-logstash-hosts, tests/40-deploy-with-kafka, tests/50-deploy-with-kafka-hosts, tests/60-test-reinstall, tests/tests.yaml
- get tests working
- add new reinstall test
- dont reset in between each test
- each test is isolated, so config changes dont affect subsequent tests -- reuse units to speed up execution.
=> amulet test work

templates/filebeat.yml
This matched *-kubernetes-worker-*, so we were excluding our container logs.
=> stop excluding kube* logs

config.yaml, templates/filebeat-5.yml, templates/filebeat-6.yml
With https://github.com/juju-solutions/layer-beats-base/pull/33, we moved logging config into the beats base layer.  Update our config to match, and fixup the v6 template spacing.
=> utilize common config and cleanup template spacing 

reactive/filebeat.py, templates/filebeat-7.yml
- use v5 template for filebeat < 6 (or any unknown version)
- s/inputs/prospectors in v6 template. 'inputs' was added after 6.2.0 but is invalid before 6.3.0. 'prospectors' appears valid for all v6.x releases.
- add v7 template
Fixes #71
=> template updates

layer.yaml
Apparently logrotate can't properly handle when its own logfile gets
rotated.
This should fix it.
=> Logrotate filebeat.log with copytruncate

config.yaml, templates/filebeat-5.yml, templates/filebeat-6.yml, templates/filebeat-7.yml
The extra_inputs config value, if specified, will inject a YAML blob
into the filebeat configuration.  This allows both for specifying
additional inputs beyond the 1-2 generated directly by the charm, and
allows for customizations specific to those additional inputs, e.g.
multiline capture settings.
=> Allow for injection of arbitrary inputs

config.yaml, reactive/filebeat.py, templates/filebeat-5.yml, templates/filebeat-6.yml, templates/filebeat-7.yml
Partial fix for https://bugs.launchpad.net/filebeat-charm/+bug/1858668
Depends on https://github.com/juju-solutions/layer-beats-base/pull/36
Use the new `has_k8s` guard for our k8s metadata processor. This ensures relevant template bits are only rendered if both `kube_logs=True` **and** `/root/.kube/config` exists.
=> update k8s metadata guard

metadata.yaml
Adding focal to the supported series as filebeat is available in the
required (default) repo.
=> Update metadata to indicate focal support

templates/filebeat-7.yml
Starting with version 7.0, Filebeat stores the registry in a sub-directory. The directory is configured using the **filebeat.registry.path** setting. 
This commit makes sure correct settings are used when installing filebeat 7.x.
=> Fix filebeat.yml template for version 7.x

templates/filebeat-5.yml, templates/filebeat-6.yml, templates/filebeat-7.yml
This change to the templates is to allow connecting to logstash using TLS, but not using the cert/key pair to do mutual authentication.
=> support using TLS only as transport 

templates/filebeat-7.yml
Reverts juju-solutions/layer-filebeat#84.
Since we don't offer a way to configure this key and filebeat starts fine without it, let's just use the default.  Backing this out in favor of #92.
=> Revert "Fix filebeat.yml template for version 7.x"

templates/filebeat-7.yml
Beats version 7 has removed filebeat.registry_file setting [1]. To reflect this
change, registry_file variable is removed from filebeat-7.yml file to support
filebeat version 7. 
To verify the behavior of the change, I have run graylog functional test. The
log can be found [here](https://pastebin.ubuntu.com/p/bSHTs2DsMZ/).
[1] https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-7.0.0.html
=> Add filebeat 7 support

README.md, charmcraft.yaml, reactive/filebeat.py, templates/filebeat-6.yml, wheelhouse.txt
**Dependency:** [This change to `layer:beats-base`](https://github.com/juju-solutions/layer-beats-base/pull/41) has to be merge as well for proper `Ubuntu 22.04` support (more info in the PR).
This change adds support for deployment of `filebeats` charm on `Ubuntu 22.04` and adds `charmcraft.yaml` file for build compatibility with `charmcraft`.
Two main changes were needed:
* Drop dependency on [charms.templating.jinja2](https://github.com/juju-solutions/charms.templating.jinja2) which depends on [Tempita](https://pypi.org/project/Tempita/) package that does not work on `python3.10` (More info in PR linked above)
* Add `clone3` syscall to list of allowed syscalls. Absence of this syscall caused an issues that are described in [this Github …
=> Ubuntu Jammy support.

metadata.yaml
The series in `metadata.yaml` file needs to be changed to `[]` to avoid conflicts with `charmcraft.yaml`.
=> Remove series in metadata.yaml

config.yaml, reactive/filebeat.py, templates/filebeat-5.yml, templates/filebeat-6.yml, templates/filebeat-7.yml
Under certain scenariosFilebeat may hold onto old
log file descriptors. There are various settings
on Filebeat to prevent this from happening. This
patch adds to the charm two key settings that
help prevent this issue:
- ignore_older
- clean_inactive
Note that while these configuration parameters used to not be specified in the filebeat config files, they will now always be rendered. The charm configuration however aligns with the upstream defaults so this is not expected to alter behavior of existing deployments upon upgrading.
Fixing: [#87](https://github.com/canonical/layer-filebeat/issues/87)
=> Fixing filebeat holding onto old file descriptors

charmcraft.yaml
`charm` was pinned to 2.x, which uses a bundled version of python (I think python3.6).
See https://forum.snapcraft.io/t/2-x-and-3-x-tracks-for-the-charm-snap/31937 . This means that the requirements resolved from wheelhouse.txt at build time are not necessarily the same requirements as would be installed at deploy time,
because the python version may be different.
So this caused missing python package dependencies during install on focal and jammy.
According to https://github.com/juju/charm-tools/issues/640 , this can be fixed by switching to `charm` 3.x,
and separating the bases
so the charm for each base is built on that base.
This ensures that the same version of python is used at build time as at runtime.
Fixes: #112
Fixes: #114
=> Split bases to fix install errors

charmcraft.yaml
libpython3-dev is required to build cython.
See https://github.com/juju-solutions/layer-basic/pull/214
This problem is only evident now since we switched to charm 3.x in charmcraft builds in https://github.com/canonical/layer-filebeat/pull/115
ref. https://review.opendev.org/c/openstack/charm-keystone-ldap/+/880084
=> Fix cython build in charmcraft build

.github/workflows/promote.yaml, .github/workflows/release.yaml
- update to latest release of charming-actions, which includes support for uploading all charm files (not just one). ref. https://github.com/canonical/charming-actions/pull/131 This is required as this charm builds one charm file for each base.
- Pin charmcraft to v2 for promote and release workflows, because the check workflow tests with v2, and we haven't tested support for charmcraft v3 yet.
=> Fix charm release
